---
wordpress:
  nodeSelector:
    kubernetes.io/arch: arm64
  tolerations:
  - effect: NoSchedule
    key: kubernetes.io/arch
    operator: Equal
    value: arm64
  service:
    type: ClusterIP
  ingress:
    enabled: true
    # ingressClassName: "nginx-external"
    annotations:
      kubernetes.io/ingress.class: "nginx-external"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      external-dns.alpha.kubernetes.io/hostname: "wordpress.cloudinterplay.com."
    hosts:
    - host: "wordpress.cloudinterplay.com"
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - secretName: certificate-tls
      hosts:
        - wordpress.cloudinterplay.com
  mariadb:
    enabled: true
    storage:
      requestedSize: 2G
    settings:
      rootPassword: dummyphrase
    userDatabase:
      name: wordpress
      user: wordpress
      password: wordpress
    tolerations:
    - effect: NoSchedule
      key: kubernetes.io/arch
      operator: Equal
      value: arm64
    nodeSelector:
      kubernetes.io/arch: arm64
